"""Remove photo_url column from Events model

Revision ID: aab756251bfa
Revises: be01383d390c
Create Date: 2024-05-20 16:01:03.562039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab756251bfa'
down_revision = 'be01383d390c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
