"""Remove Instructor model

Revision ID: abaa33f1e986
Revises: aab756251bfa
Create Date: 2024-05-23 11:14:43.103337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abaa33f1e986'
down_revision = 'aab756251bfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instructor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructor',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('occupation', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('brief_bio', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('user_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], name='instructor_user_token_fkey'),
    sa.PrimaryKeyConstraint('id', name='instructor_pkey')
    )
    # ### end Alembic commands ###
