"""Added photo_url column to Events

Revision ID: be01383d390c
Revises: d3c4b3187f4c
Create Date: 2024-05-18 00:40:25.580321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be01383d390c'
down_revision = 'd3c4b3187f4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###
